### ISSUE TITLE
FR: Unsubscribe from notifications

### ISSUE THREAD

**Issue by leeaston** [verbb/comments#11]
Hi Josh, when you get round to email notifications, it would useful to be able to unsubscribe to further notifications by clicking an unsubscribe link in the email notification itself.

Will you be selling and supporting this plugin long term?

**Comment by engram-design** [comment]
For sure. Definitely need to put some thought into the entire notifications system - something that's down the track at this stage. You may have noticed in other issues the discussion around that!

My aim is to eventually sell this through the official Craft plugin store, and not before then. The code here will always be available and free. I certainly don't want to charge much (like around $10), purely so that I can dedicate time to giving support for this plugin.

Until then, I'll be doing my best to create a full-featured plugin, thats freely available :)
