### ISSUE TITLE
Idea: Make it realtime / chat alike

### ISSUE THREAD

**Issue by johanneslamers** [verbb/comments#14]
https://pusher.com/tutorials/realtime_chat_widget

**Comment by engram-design** [comment]
Great idea, although this is something that won't be put into the core directly - purely because I want to give integrators the freedom to craft whatever solution they want for comments.

Having said that - I'd like to provide a full-featured example using pusher, ajax, and traditional. From a quick look at the Pusher docs, I could put together a tutorial (wiki page) to explain how this can be done.

Nice!

**Comment by johanneslamers** [comment]
Yeah! Nice Josh!

2015-03-28 23:05 GMT+01:00 Josh Crawford <notifications@github.com>:

> Great idea, although this is something that won't be put into the core
> directly - purely because I want to give integrators the freedom to craft
> whatever solution they want for comments.
>
> Having said that - I'd like to provide a full-featured example using
> pusher, ajax, and traditional. From a quick look at the Pusher docs, I
> could put together a tutorial (wiki page) to explain how this can be done.
>
> Nice!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/engram-design/Comments/issues/14#issuecomment-87321191>
> .
>



-- 
Lamers Vormgeving
----------------------------
Johannes Lamers
V T v Serooskerkenplein 36-1
1076 NB  Amsterdam
----------------------------
T: 0647558368
E: johanneslamers@gmail.com

**Comment by lettie16** [comment]
Did you manage to put together a wiki tutorial for this?

**Comment by engram-design** [comment]
@lettie16 It never got implemented, and likely won't for the Craft 2 version of the plugin. Maybe for Craft 3, but not on our immediate todo list.

**Comment by engram-design** [comment]
No immediate plans for this thanks to the inbuilt, Ajax-driven default templates. Its a much more advanced tutorial than the scope of the plugin.

Maybe one day!
