### ISSUE TITLE
Can't fetch votes for a comment any more

### ISSUE THREAD

**Issue by martinhellwagner** [verbb/comments#143]
### Description

We're experiencing a recent problem with our Comments plugin. All of a sudden, the votes of a comments can't be loaded any more with `{{ myComment.votes }}` in Twig (where `myComment` is the current Comment Object). Things like `{{ myComment.comment }}` work without problems. The votes for each comment just yield _null_. In the database, the comment as well as its vote(s) are correctly inserted though (see screenshots below).

### Steps to reproduce

1. Try to fetch votes from a comment by calling `{{ myComment.votes }}` in the Twig template

### Additional info

- Plugin version: 1.1.0
- Craft version: 3.1.5

**Comment by martinhellwagner** [comment]
**Comment**

![Screenshot 2019-11-11 at 12 04 33](https://user-images.githubusercontent.com/19146752/68583162-d2f5c780-047c-11ea-8094-2a1622a2b4de.png)

**Vote**

![Screenshot 2019-11-11 at 12 04 39](https://user-images.githubusercontent.com/19146752/68583163-d38e5e00-047c-11ea-922d-2bbf1016aea1.png)

**Comment by engram-design** [comment]
Can't seem to replicate this one, and in fact, most of the time this should return `0` rather than null. This is because the SQL query is returning `count()` on the query.

I'll look into it further to see what I can do to replicate it. What's your MySQL version?

I'll also mention that 1.1.0 is pretty out of date (almost a year), so even an update might help, although there haven't been any fixes for this problem specifically I don't think.

**Comment by martinhellwagner** [comment]
We're running MySQL 8.0.16 on our server. Will update the plugin and see if that helps.
Thanks for now! 🙂

**Comment by martinhellwagner** [comment]
This seems to have been fixed with 1.3.6, I see. Thus, I'll be closing this issue. Thanks! 👍
