### ISSUE TITLE
Argument 1 passed to craft\services\Structures::appendToRoot() must be of the type int, null given, called in /var/web/vd15140/releases/20200405172647/vendor/verbb/comments/src/elements/Comment.php on line 842

### ISSUE THREAD

**Issue by cookie10codes** [verbb/comments#176]
### Description
Local everything works fine, but on staging this error appears when setting a comment.

### Additional info

- Plugin version: 1.3.9 -> minor change om CommentsService.php to fix it

**Comment by cookie10codes** [comment]
I think in your main Comments.php you should add the check on line 102 if Db::idByUid(Table::STRUCTURES, $this->structureUid) exists

**Comment by engram-design** [comment]
Should be fixed in [1.3.10](https://github.com/verbb/comments/releases/tag/1.3.10)

Please note that you'll need to run `./craft project-config/rebuild` on your staging server, if at all possible. 

If not, you'll need to look in your `project.yaml` file, find the `structureUid` property for the comments plugin. Find the corresponding row in your local database, in the `structures` database table. Copy this row, or at least take note of the values. On your staging server, duplicate this row exactly, ensuring the UID is exactly the same.

The last step is really just a repair of not pushing the structure-creation step when it should've been occurring, during project config updates.
