### ISSUE TITLE
FR: UI / UX problem on sites with lots of entries

### ISSUE THREAD

**Issue by johanneslamers** [verbb/comments#3]
In the comment control panel you have a sidebar left with all the entries that with comments. What if the site has like 5000 entries with comments. The left sidebar gets cluttered.

**Comment by engram-design** [comment]
Thats true - it's almost redundant having that there at all, because its a column in the table. Maybe it's a better idea to group by section? What would be the most useful grouping?

**Comment by johanneslamers** [comment]
Group by section would be nice.

**Comment by lukeholder** [comment]
My ideas:

Show all comments in the current view, but use the sources on the left to filter by elementtype the comment is attached to. (make the plugin work with any element, not just entries)

Make a fieldtype that shows a listing of the comments on the current element with basic management actions in a table, and then a  link to the edit comment which would take you to your current edit comment screen.

**Comment by engram-design** [comment]
The plan is to work with any element for v1.0. Just haven't had a chance to look into how this is best done yet!

Great suggestion though Luke :)

**Comment by lukeholder** [comment]
happy to contribute once you put a friendly licence on the repo.

**Comment by engram-design** [comment]
The sidebar is now grouped by section for the moment.

**Comment by gglnx** [comment]
Is this still the case? I see elements in the sidebar, not sections.

**Comment by engram-design** [comment]
@

**Comment by engram-design** [comment]
@gglnx This was semi-reverted recently, but have improved it back to the way it was previously in in [1.2.0](https://github.com/verbb/comments/releases/tag/1.2.0).

I've added a config setting `indexSidebarIndividualElements`, which is default to true, so that individual comments are shown in the sidebar. You can also play around with the `indexSidebarLimit` settings, which is default to 25, so you won't get a billion items in the sidebar.

Lastly, I've also added grouping entries, which you can also control via `indexSidebarGroup`.
