### ISSUE TITLE
Can voting and flagging be anonymous?

### ISSUE THREAD

**Issue by Djive** [verbb/comments#90]
We would like to have only anonymous comments (just name and email, no user accounts).
We would also like to have ability to flag and vote on comments.

I know it might invite random downvoting and flagging, but since the comment doesn't get deleted, it only serves as notification to admin to check the comment in question.

Comments 1.0.2 
Craft CMS 3.0.25

Thanks!

**Comment by engram-design** [comment]
The issue here is really around preventing abuse of voting, as you've mentioned, but specifically so that users can't vote or flag multiple times. Currently, if you up/down vote something, you can only do this once. This is tracked by your email - arguably the only reliable source of identifiable information about you. Similarly with flagging.

I'm very hesitant to add this in, even as a configurable option, just because it'll require a bit of rework to change how voting is validated. I'll give it some thought!

**Comment by Djive** [comment]
Much appreciated!

**Comment by Coalescent** [comment]
While not exactly trivial to do I'd guess - and still potentially open to abuse - you could handle this scenario with cookies. I think if someone wanted to allow anonymous voting/flagging, the likelihood of abuse by removing those cookies is probably pretty slim.

**Comment by engram-design** [comment]
Added in [1.3.6](https://github.com/verbb/comments/releases/tag/1.3.6)
